<h4> Biblioteka numpy

In [21]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


<h4> Lista a array

In [2]:
x = [1,2,3]
print(dir(x))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [3]:
y = np.array(x)
print(dir(y))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [4]:
len(a)

8

In [5]:
a[1:7]

array([2, 3, 4, 5, 6, 7])

In [6]:
a[1:7:2]

array([2, 4, 6])

In [7]:
a = np.append(a,22)

In [8]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8, 22])

In [9]:
x1 = np.array([1,2,5,6,1,1,0])
x2 = np.array([-1,7,13,2,0,0,1]) 

In [10]:
x1+x2

array([ 0,  9, 18,  8,  1,  1,  1])

In [1]:
x1 = [1,2,5,6,1,1,0]
x2 = [-1,7,13,2,0,0,1]
x1+x2

[1, 2, 5, 6, 1, 1, 0, -1, 7, 13, 2, 0, 0, 1]

In [12]:
#Wszystkie podstawowe funkcje matematyzne też znajdują sie w numpy

x = np.array([1,2,3,4,5,6])
y = np.sin(x) #liczy wartość funkcji sinus na każdym elemencie x
print(y)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


<h4> Macierze jako array 2D

In [13]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
A.shape #wymiar

(4, 3)

In [15]:
Z = np.zeros((3, 5)) #macierz zerowa o 3 wierszach i 5 kolumnach
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


<h4> Operacje na macierzach

In [16]:
A = np.array([
    [1,2],
    [3,4],
])

B = np.array([
    [5,6],
    [7,8]
])

In [17]:
A+B #dodawanie macierzy

array([[ 6,  8],
       [10, 12]])

In [18]:
A-B #odejmowanie macierz

array([[-4, -4],
       [-4, -4]])

In [19]:
A*B #mnożenie macierzy element po elemencie

array([[ 5, 12],
       [21, 32]])

In [20]:
np.dot(A,B) #właściwe mnożenie macierzy

array([[19, 22],
       [43, 50]])

In [21]:
A+7 #dodaj 7 do każdej wartości macierzy A

array([[ 8,  9],
       [10, 11]])

In [22]:
X = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
X.shape

(3, 4)

In [24]:
X.reshape((6,2)) #zmiana kształtu

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [25]:
np.linalg.inv(A) #macierz odwrotna

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [26]:
np.linalg.det(A) #wyznacznik macierzy A

-2.0000000000000004

<h4> Zadanie1: Zdefiniuj dowolne dwie macierze kwadratowe $A$ i $B$ o wymiarach (3,3) (trzy kolumny i trzy wiersze). Przekonaj się, że mnożenie macierzy nie jest przemienne, tj. $AB$ i $BA$ to różne macierze.

<h4> Zadanie2: Wyznacz macierz $B^4+AB+6B^{-1}A$, gdzie $A$ i $B$ zdefiniowane w poprzednim zadaniu.

In [27]:
#Wstawka/f-stringi

x = 12.456
print(f'Zmienna x wynosi {x:.2f}')

Zmienna x wynosi 12.46


<h4> Regresja liniowa z użyciem algorytmu Backward

In [25]:
#Dane do treningu###########################
X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([7, 9, 11, 13]) #czyli Y = a*X + b,  gdzie a=2, b=5
############################################

#Parametry początkowe#######################
a = 1.0
b = 1.0
############################################


#Postać modelu
def forward(x):
    return a*x+b

#Funkcja kosztu
def loss(y, y_pred):
    return np.mean(((y_pred - y)**2))

#Gradient
def gradient(x, y, y_pred):
    return np.mean(2*x*(y_pred - y)), np.mean(2*(y_pred - y)) #pochodne (po funkcji kosztu), obliczone ręcznie


print(f'Ile wynosi f(5): {forward(5):.3f}')


#Trenowanie########################################
learning_rate = 0.01 #współczynnik uczenia 
n_iters = 1000 #liczba iteracji

for epoch in range(n_iters):
    y_pred = forward(X) #liczymy ile wynoszą przewidywane wartości dla X
    l = loss(Y, y_pred) #wyznaczamy wartość funkcji kosztu
    dl = gradient(X, Y, y_pred) #liczymy gradient
    a -= learning_rate * dl[0]    #aktualizujemy parametr a
    b -= learning_rate * dl[1]    ##aktualizujemy parametr b
    
    if epoch % 200 == 0: #Co 200 przejscie zobaczmy parametry i wartosc funkcji kosztu
        print(f'epoch {epoch+1}: a = {a:.3f}, b = {b:.3f}, loss = {l:.8f}')
  
print(f'Ile wynosi f(5) po trenowaniu: {forward(5):.3f}')

Ile wynosi f(5): 6.000
epoch 1: a = 1.350, b = 1.130, loss = 43.50000000
epoch 201: a = 2.611, b = 3.204, loss = 0.54165851
epoch 401: a = 2.335, b = 4.014, loss = 0.16324936
epoch 601: a = 2.184, b = 4.459, loss = 0.04920135
epoch 801: a = 2.101, b = 4.703, loss = 0.01482869
Ile wynosi f(5) po trenowaniu: 15.115


<h4> Zadanie3: Zdefiniuj dane uczące  X=np.array([1,2,3,4,5])  oraz  Y=np.array([−1,3,13,29,51]) . Zakładamy, że pomiędzy  X  i  Y  istnieje przybliżona zależność $Y=aX^2+bX+c$. Zbuduj model przewidujący wartość parametrów  a,b,c  w oparciu o  X  i  Y. Następnie wyznacz przewidywaną wartość dla  x=6 .

<h4> Zadanie4: Zdefiniuj dane uczące  X=np.array([−3,−2,−1,0,1,2,3])  oraz  Y=np.array([27,−32,−13,0,−5,32,243]) . Zakładamy, że pomiędzy  X  i  Y  istnieje przybliżona zależność  $Y=aX^4+bX^3+cX^2+dX+e$. Zbuduj model przewidujący wartość parametrów  a,b,c,d,e  w oparciu o  X  i  Y . Przetestuj trzy rodzaje parametrów:

- parametry początkowe: a=0, b=0, c=0, d=0, e=0; learning_rate=0.01; n_iters = 10

- parametry początkowe: a=0, b=0, c=0, d=0, e=0; learning_rate=0.0001; n_iters = 10

- parametry początkowe: a=0, b=0, c=0, d=0, e=0; learning_rate=0.0001; n_iters = 10000

- parametry początkowe: a=2.7, b=4.2, c=-11.9, d=0.1, e=0; learning_rate=0.0001; n_iters = 10000

wyświetlając za każdym razem tylko 5 epok z modelu (w równych odstępach czasu). Skomentuj otrzymane wyniki

<h4> Biblioteka PyTorch - wprowadzenie

In [5]:
import torch 

In [30]:
#tworzenie tensorow 1D

t1 = torch.tensor([1,2,3,4,6])
print(t1)

tensor([1, 2, 3, 4, 6])


In [31]:
#tworzenie tensorow 2D

t2 = torch.tensor([[1,2,3,4,6],[7,6,-2,1,0]])
print(t2)

tensor([[ 1,  2,  3,  4,  6],
        [ 7,  6, -2,  1,  0]])


In [32]:
t2[0] #elementy tensora 2D to tensory 1D

tensor([1, 2, 3, 4, 6])

In [33]:
#tworzenie tensorow 3D

t3 = torch.tensor([[[1,3], [5,-1]],[[0,4], [10,11]]])
print(t3)

tensor([[[ 1,  3],
         [ 5, -1]],

        [[ 0,  4],
         [10, 11]]])


In [34]:
t3[0] #elementy tensora 3D to tensory 2D

tensor([[ 1,  3],
        [ 5, -1]])

<h4> Operacje na tensorach

In [35]:
#tworzę dwa tensory 1D

x  = torch.tensor([4,7])
y  = torch.tensor([-2,3])

In [36]:
z1 = x+y #dodawanie tensorow
print(z1)

tensor([ 2, 10])


In [37]:
z2 = x*y #mnożenie tensorow
print(z2)

tensor([-8, 21])


In [38]:
#Tensor zerowy o zadanych wymiarach
a = torch.zeros([2,5])
print(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [39]:
a.shape #wymiary tensora a

torch.Size([2, 5])

<h4> Tensory losowe

In [40]:
b1 = torch.rand([4,3]) #tensor liczb losowych z rozkładu jednostajnego
print(b1)

tensor([[0.4820, 0.3024, 0.6173],
        [0.6214, 0.1780, 0.4908],
        [0.9264, 0.3585, 0.3858],
        [0.4100, 0.3380, 0.6361]])


In [41]:
b2 = torch.randn([3, 4, 5]) #tak jak wyzej, tylko tym razem z rozkladu normalnego/Gaussa [literka n na koncu]
print(b2)

tensor([[[-0.6423, -1.4874, -0.4804,  0.9581, -0.6918],
         [-0.7581, -0.8823, -0.1709, -0.5210,  0.9010],
         [-0.1989, -0.9266, -0.9507, -0.2836, -1.2085],
         [ 1.2416, -0.5363, -0.7282, -0.3636,  0.5127]],

        [[ 0.7013,  0.3208,  1.5537,  0.6296, -1.8385],
         [ 2.1334,  1.3272,  1.0909,  1.7875, -1.7143],
         [-1.4874,  1.0700, -1.8206,  0.3654, -0.4310],
         [-1.1849, -0.7481, -0.9042, -0.4140, -0.6792]],

        [[-0.2982,  0.9868,  0.4614,  0.2485, -1.2234],
         [ 0.1962,  0.0845,  1.5312, -0.7911, -1.3818],
         [-0.7243, -0.9855, -1.2512, -1.1951, -0.0168],
         [-0.3802,  0.3688,  0.5359, -0.3501,  0.0542]]])


In [42]:
c1 = b1.view([1,12])  #view pełni te samą funkcję co reshape w numpy
print(c1)

tensor([[0.4820, 0.3024, 0.6173, 0.6214, 0.1780, 0.4908, 0.9264, 0.3585, 0.3858,
         0.4100, 0.3380, 0.6361]])


In [43]:
c2 = b1.view([2,6])  #view pełni te samą funkcję co reshape w numpy
print(c2)

tensor([[0.4820, 0.3024, 0.6173, 0.6214, 0.1780, 0.4908],
        [0.9264, 0.3585, 0.3858, 0.4100, 0.3380, 0.6361]])


In [44]:
c3 = b1.view([2,-1])  #jezeli ustawie index na -1 to zostanie ustawiony domyslny rozmiar na tej pozycji (tak zeby było ok, przy załozonej wartosci drugiego indeksu)
print(c3)

tensor([[0.4820, 0.3024, 0.6173, 0.6214, 0.1780, 0.4908],
        [0.9264, 0.3585, 0.3858, 0.4100, 0.3380, 0.6361]])


In [45]:
c4 = b1.view([-1,2])  
print(c4)

tensor([[0.4820, 0.3024],
        [0.6173, 0.6214],
        [0.1780, 0.4908],
        [0.9264, 0.3585],
        [0.3858, 0.4100],
        [0.3380, 0.6361]])


<h4> Zadanie5. Utwórz dwa tensory jednowymiarowe  x=tensor([1,2,3,4,5,6])  oraz  y=tensor([7,8,3,−1.,−2,2]) . Następnie wyznacz nowy tensor wg przepisu  $z=x^3+2y$. Utwórz dwa nowe tensory (2D - o wymiarach 2 na 3 oraz 3D - o wymiarach 2,1,3 odpowiednio) poprzez zmianę wymiaru  z .

<h4> Typy liczbowe

In [46]:
x1 = torch.tensor([1,2,3]) 
print(x1)     

tensor([1, 2, 3])


In [47]:
x2 = torch.tensor([1.0,2,3])  
print(x2)

tensor([1., 2., 3.])


<h4> Konkatenacja

In [48]:
x1 = torch.randn(2, 5)
x2 = torch.randn(3, 5)
y = torch.cat([x1, x2]) #domyślnie konkatenuje wiersze 

print(y)

tensor([[ 1.3889,  0.4623, -0.1972,  0.5615, -0.6790],
        [-2.7907,  0.0381, -0.3735, -1.4054,  1.7846],
        [ 0.4469,  0.8596,  0.3873, -0.8999, -0.3291],
        [-2.4238,  0.9740,  0.1313,  0.2889,  2.0592],
        [ 0.2495,  0.2077, -0.9615, -0.0966,  0.4031]])


In [49]:
x1 = torch.randn(2,3)
x2 = torch.randn(2,5)
y = torch.cat([x1, x2], 1) #teraz konkatenuje po kolumnach

print(y)

tensor([[-0.4553,  0.1454, -0.2270,  1.6258,  0.9062,  0.9873, -0.3742, -0.7640],
        [-0.7893,  0.9054,  0.1424, -0.9897,  0.0746, -0.4261, -0.5836,  0.3055]])


Uwaga: Aby wykonać konkatenację, liczba wierszy/liczba kolumn musi być zgodna w obu Tensorach.


<h4> Po co Tensory skoro mamy Array z numpy?

In [10]:
x = torch.tensor([3.0, -1.0, 2.0], requires_grad=True)

In [51]:
print(x)  #tensor + jakaś dodatkowa informacja, po co? za chwile

tensor([ 3., -1.,  2.], requires_grad=True)


In [52]:
print(x.data) #sam tensor

tensor([ 3., -1.,  2.])


In [17]:
x = torch.tensor([1.0,2,3], requires_grad=True)
y = torch.tensor([-4.0,3,7], requires_grad=True)

z = x+y

In [18]:
print(z.data) #sam wynik dodawania [w tym momencie nie wazne jakie było x i y, mamy ich sume/nie ma pamieci przeszlosci]

tensor([-3.,  5., 10.])


In [19]:
print(z.grad_fn) #dodatkowa informacja, Add - czyli wiadomo ze 'z' powstalo przez zsumowanie jakis innych Tensorow

In [56]:
print(z) #tutaj obie informacje

tensor([-3.,  5., 10.], grad_fn=<AddBackward0>)


In [57]:
r = z.sum() #r powstlo przez zsumowanie elementow Tensora z, co więcej - s pozwala nawet policzyć pochodną, patrz niżej:
print(r)

tensor(12., grad_fn=<SumBackward0>)


<h4> Wstawka matematyczna:

$r=\underbrace{x_0+y_0}_{\text{z0}}+\underbrace{x_1+y_1}_{\text{z1}}+\underbrace{x_2+y_2}_{\text{z2}}$

Ile wynoszą:  $\frac{\partial r}{\partial x_0}$, $\frac{\partial r}{\partial x_1}$, $\frac{\partial r}{\partial x_2}$?


In [58]:
r.backward() #stosujemy algorytm wstecznej propagacji (back propagation algorithm) do r

In [59]:
print(x.grad) #pochodna r po zmiennej x = (x0,x1,x2)

tensor([1., 1., 1.])


Uwaga: Jeżeli wykonasz powyższe 2 linijki wiele razy, gradient będzie się zwiększał. Inaczej mówiąc gradient się akumuluje (dla wielu modeli to użyteczna własność, którą zaproponowali autorzy PyTorch).

In [60]:
r.backward()
print(x.grad) 

tensor([2., 2., 2.])


In [61]:
r.backward()
print(x.grad) 

tensor([3., 3., 3.])


In [62]:
x.grad.zero_() #jeżeli chce wyzerowac gradient

tensor([0., 0., 0.])

In [63]:
print(x.grad) 

tensor([0., 0., 0.])


In [64]:
r.backward()
print(x.grad)

tensor([1., 1., 1.])


<h4> Zadanie6: Wyjaśnij poniższe liniki kodu i otrzymany wynik (łącznie z uzyskanymi wartościami w x.grad)


In [65]:
x = torch.tensor([-3.0,4,1], requires_grad=True)
z = x**3
r = z.sum()
print(r)
r.backward()
print(x.grad)

tensor(38., grad_fn=<SumBackward0>)
tensor([27., 48.,  3.])


<h4> Zadanie7: Wyjaśnij poniższe liniki kodu i otrzymany wynik (łącznie z uzyskanymi wartościami w x.grad)

In [66]:
x = torch.tensor([-3.0,4,1], requires_grad=True)
y = torch.tensor([2.0,0,-1], requires_grad=True)
z = (x**2)*y
r = z.sum()
print(r)
r.backward()
print(x.grad)

tensor(17., grad_fn=<SumBackward0>)
tensor([-12.,   0.,  -2.])
